r"""
================================================================================
1. PURPOSE & ROLE:
   - Module: src/pipeline_3_generation/citation_check.py
   - Role: Citation validation and Unicode normalization engine.
   - Purpose: Parses inline citation tags, standardizes Unicode/full-width bracket
     variations (e.g., `【Doc-1】`, `［Doc-1］`, `［1］` -> `[Doc-1]`), normalizes non-breaking
     whitespace (`\u202f`, `\xa0`), validates document index bounds against retrieved context set,
     and creates strictly typed `GeneratedDraft` objects.

2. INPUT (IP):
   - draft_text (str): Raw generated draft text from `src/pipeline_3_generation/generator.py`.
   - max_valid_doc_id (int): Total number of valid candidate documents supplied in the prompt.

3. PROCESS UNDER THE HOOD:
   - Step 1: Applies canonical Unicode NFKC normalization (`unicodedata.normalize('NFKC', draft_text)`).
   - Step 2: Normalizes non-breaking and narrow whitespace (`\u202f`, `\xa0` -> `' '`).
   - Step 3: Canonicalizes citation tag variations (`[1]`, `[Doc 1]`, `[Doc:1]`, `[doc_1]`, `【Doc-1】`)
     into standard `[Doc-X]` format via generalized regex `r"\[\s*(?:Doc[\s:_-]*)?(\d+)\s*\]"`.
   - Step 4: Discovers all inline document references via `r'\[Doc-(\d+)\]'`.
   - Step 5: Validates that every extracted index satisfies: `1 <= doc_index <= max_valid_doc_id`.
   - Step 6: If any citation references an index `< 1` or `> max_valid_doc_id`, marks `citations_valid=False`.
   - Step 7: Collects unique citation tags and sorts them numerically: `["Doc-1", "Doc-2", ...]`.
   - Packages normalized result into Pydantic schema `GeneratedDraft`.

4. OUTPUT (OP):
   - GeneratedDraft: Strict Pydantic model containing:
     * raw_text (str): Cleaned, normalized draft text.
     * cited_doc_ids (list[str]): Sorted unique document handles.
     * citations_valid (bool): True if all citations are within bounds.
   - Consumed by: `src/pipeline_4_verification/` for claim extraction and NLI auditing.

5. LIBRARIES & DEPENDENCIES:
   - re: Standard library for regular expression normalization and extraction.
   - unicodedata: Standard library for canonical NFKC Unicode normalization.
   - src.common.schemas.GeneratedDraft: Typed data contract for generated drafts.
================================================================================
"""

import re
import unicodedata
from typing import List, Set
from src.common.schemas import GeneratedDraft


def validate_and_parse_citations(draft_text: str, max_valid_doc_id: int) -> GeneratedDraft:
    """Extract, normalize, and validate all inline document citations from generated text.

    Args:
        draft_text: Raw text generated by LLM / Generator.
        max_valid_doc_id: Maximum valid document index based on prompt context count.

    Returns:
        GeneratedDraft instance with normalized text, parsed document IDs, and validity status.
    """
    if not draft_text:
        return GeneratedDraft(
            raw_text="",
            cited_doc_ids=[],
            citations_valid=True,
        )

    # 1. Apply canonical Unicode NFKC normalization (automatically converts Asian fullwidth brackets, numbers, and symbols)
    normalized = unicodedata.normalize("NFKC", draft_text)

    # 2. Normalize non-breaking and narrow whitespace
    normalized = normalized.replace("\u202f", " ").replace("\xa0", " ")

    # 3. Normalize all Asian and Unicode bracket variants
    normalized = (
        normalized.replace("【", "[")
        .replace("】", "]")
        .replace("〔", "[")
        .replace("〕", "]")
        .replace("〖", "[")
        .replace("〗", "]")
        .replace("〘", "[")
        .replace("〙", "]")
    )

    # 4. Expand composite multi-citation brackets ([Doc-1, Doc-2], [1, 2]) and normalize to [Doc-X]
    def _expand_bracket(match: re.Match) -> str:
        inner = match.group(1)
        digits = re.findall(r"(?:Doc[\s:_-]*)?(\d+)", inner, flags=re.IGNORECASE)
        if digits:
            return "".join(f"[Doc-{d}]" for d in digits)
        return match.group(0)

    normalized = re.sub(r"\[([^\]\n]+)\]", _expand_bracket, normalized)
    normalized = re.sub(r"\[\s*(?:Doc[\s:_-]*)?(\d+)\s*\]", r"[Doc-\1]", normalized, flags=re.IGNORECASE)

    # 5. Find all occurrences of canonical [Doc-X]
    matches = re.findall(r"\[Doc-(\d+)\]", normalized)

    citations_valid = True
    found_doc_nums: Set[int] = set()

    for match in matches:
        doc_num = int(match)
        found_doc_nums.add(doc_num)
        if doc_num < 1 or doc_num > max_valid_doc_id:
            citations_valid = False

    # Sort unique document tags in numerical order
    sorted_doc_ids: List[str] = [f"Doc-{num}" for num in sorted(found_doc_nums)]

    return GeneratedDraft(
        raw_text=normalized,
        cited_doc_ids=sorted_doc_ids,
        citations_valid=citations_valid,
    )
